name: xoxo
description: "A new Flutter project with Tic-Tac-Toe game and splash screen."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  flutter_lints:
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
     - assests/sounds/splash_sound.mp3
     - assests/sounds/lose_sound.mp3
     - assests/ass.png
